# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    tags:
    - 'c-*'
    branches: [ main ]
  pull_request:
    tags:
    - 'c-*'
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Setup MSBuild Path
        uses: warrenbuckley/Setup-MSBuild@v1
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
    
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.2
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
     
      - name: Checkout Files
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # for nbgv  - fetch-depth: 0
        uses: actions/checkout@v2
        with:
          fetch-depth: 0        

      - name: Build solution
        run: |
          cd demoFramework
          nuget restore demoFramework.sln
          msbuild demoFramework.sln /p:Configuration=Release 
      - name: Zip release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: 'release.zip'
          directory: 'bin\Release'
      - name: Publis Release by tag
        uses: ncipollo/release-action@v1
        with:
          artifacts: "demo/bin/Debug/net6.0/release.zip"
          body: 'test body <b>bold</b>'
          # commit: 'main'
          # tag: "rel2"
          token: ${{ secrets.GITHUB_TOKEN }}
      
          
